### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by devios1337** [Jaspersoft/js-ios-app#1]
I've included the JasperMobile iOS SDK 1.8 in the expected location relative to the project, which resolved the initial build issues. (Btw, the readme says "This project includes the SDK files as part of the source." which isn't true. I had to download it separately and install it. The "jaspersoft-sdk" directory in the repo is empty.) However I'm now getting compile issues that seem as though I'm linking against the wrong library, even though the readme says it requires version 1.8 of the SDK.

I'm seeing about 50 compile errors including things like:

JMInputControlCell.m:44:62: No visible @interface for 'JSInputControlDescriptor' declares the selector 'errorString'

JMSaveReportViewController.m:183:13: Unknown type name 'JSExportExecutionResponse'; did you mean 'JSReportExecutionResponse'?

JMSaveReportViewController.m:187:79: Property 'uuid' not found on object of type 'JSReportExecutionResponse *'

JMReportOptionsViewController.m:179:29: Property 'ICD_TYPE_SINGLE_VALUE_TIME' not found on object of type 'JSConstants *'

I did a project-wide string search for "ICD_TYPE_SINGLE_VALUE_TIME" and found only the one reference to it, but not definition. It seems I am still missing some files or libraries.

**Comment by ogubariev** [comment]
Thanks! We already fixed this issue. You can try again.
